sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
  packaging-dev
script:
- rm -rf .git
- cd $TOPDIR
- wget https://bintray.com/rwth-os/hermitcore/download_file?file_path=binutils-hermit_2.26.1-1_amd64.deb -O binutils-hermit_2.26.1-1_amd64.deb
- sudo dpkg -i ./binutils-hermit_2.26.1-1_amd64.deb
- wget https://bintray.com/rwth-os/hermitcore/download_file?file_path=newlib-hermit_2.4.0-1_amd64.deb -O newlib-hermit_2.4.0-1_amd64.deb
- sudo dpkg -i ./newlib-hermit_2.4.0-1_amd64.deb
- wget https://bintray.com/rwth-os/hermitcore/download_file?file_path=pthread-embedded-hermit_1.0-1_amd64.deb -O pthread-embedded-hermit_1.0-1_amd64.deb
- sudo dpkg -i ./pthread-embedded-hermit_1.0-1_amd64.deb
- wget https://www.lankes.org/deploy/bootstrap.tar.gz
- tar xzf bootstrap.tar.gz
- mkdir -p $TOPDIR/tmp/bootstrap
- cd $TOPDIR/tmp/bootstrap
- $TOPDIR/RWTH-OS/gcc/configure --target=x86_64-hermit --prefix=$TOPDIR/x86 --without-headers --with-newlib --with-isl --disable-multilib --with-tune=generic --enable-languages=c,c++,lto --disable-nls --disable-shared --disable-libssp --enable-threads=posix --disable-libgomp --enable-tls --enable-lto --disable-symvers --with-headers=/opt/hermit/x86_64-hermit/include
- make -j2
- make install
- mkdir -p $TOPDIR/tmp/gcc
- cd $TOPDIR/tmp/gcc
- $TOPDIR/RWTH-OS/gcc/configure --target=x86_64-hermit --prefix=$TOPDIR/x86 --without-headers --with-newlib --with-isl --disable-multilib --with-tune=generic --enable-languages=c,c++,fortran,go,lto --disable-nls --disable-shared --disable-libssp --enable-threads=posix --disable-libgomp --enable-tls --enable-lto --disable-symvers --with-headers=/opt/hermit/x86_64-hermit/include
- make -j2
- make install
env:
   global:
     - TOPDIR=/home/travis/build
     - PATH=$PATH:/opt/hermit/bin/:$TOPDIR/x86/bin
