sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y gcc g++ nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev packaging-dev
script:
- rm -rf .git
- cd ..
- mv gcc gcc-5.3.1
- tar czf gcc_5.3.1.orig.tar.gz gcc-5.3.1
- cd $TOPDIR
- wget https://bintray.com/rwth-os/hermitcore/download_file?file_path=binutils-hermit_2.26.1-1_amd64.deb -O binutils-hermit_2.26.1-1_amd64.deb
- sudo dpkg -i ./binutils-hermit_2.26.1-1_amd64.deb
- wget https://bintray.com/rwth-os/hermitcore/download_file?file_path=newlib-hermit_2.4.0-1_amd64.deb -O newlib-hermit_2.4.0-1_amd64.deb
- sudo dpkg -i ./newlib-hermit_2.4.0-1_amd64.deb
- wget https://bintray.com/rwth-os/hermitcore/download_file?file_path=pthread-embedded-hermit_1.0-1_amd64.deb -O pthread-embedded-hermit_1.0-1_amd64.deb
- sudo dpkg -i ./pthread-embedded-hermit_1.0-1_amd64.deb
- wget https://www.lankes.org/deploy/bootstrap.tar.gz
- tar xzf bootstrap.tar.gz
- mkdir -p $TOPDIR/tmp/bootstrap
- cd $TOPDIR/tmp/bootstrap
- $TOPDIR/RWTH-OS/gcc-5.3.1/configure --target=x86_64-hermit --prefix=/opt/hermit --without-headers --with-newlib --with-isl --disable-multilib --with-tune=generic --enable-languages=c,c++,lto --disable-nls --disable-shared --disable-libssp --enable-threads=posix --disable-libgomp --enable-tls --enable-lto --disable-symvers --quiet --enable-silent-rules
- make -j2 all
- sudo make install
- cd $TOPDIR/RWTH-OS/gcc-5.3.1
- rm -rf $TOPDIR/x86/bin
- debuild -e PATH -e FC_FOR_TARGET=x86_64-hermit-fc -e CC_FOR_TARGET=x86_64-hermit-gcc -e CXX_FOR_TARGET=x86_64-hermit-g++ -e GCC_FOR_TARGET=x86_64-hermit-gcc -e CPP_FOR_TARGET=x86_64-hermit-cpp -e AR_FOR_TARGET=x86_64-hermit-ar -e AS_FOR_TARGET=x86_64-hermit-as -e LD_FOR_TARGET=x86_64-hermit-ld -e OBJDUMP_FOR_TARGET=x86_64-hermit-objdump -e OBJCOPY_FOR_TARGET=x86_64-hermit-objcopy -e RANLIB_FOR_TARGET=x86_64-hermit-ranlib -e STRIP_FOR_TARGET=x86_64-hermit-strip -e READELF_FOR_TARGET=x86_64-hermit-readelf -e ELFEDIT_FOR_TARGET=x86_64-hermit-elfedit -e NM_FOR_TARGET=x86_64-hermit-nm -e CFLAGS_FOR_TARGET="-m64 -mtls-direct-seg-refs -O3 -ftree-vectorize" -e FCFLAGS_FOR_TARGET="-m64 -mtls-direct-seg-refs -O3 -ftree-vectorize" -e FFLAGS_FOR_TARGET="-m64 -mtls-direct-seg-refs -O3 -ftree-vectorize" -e CXXFLAGS_FOR_TARGET="-m64 -mtls-direct-seg-refs -O3 -ftree-vectorize" -uc -us
- ls -l /opt/hermit/bin
deploy:
  on: production
  provider: bintray
  file: .bintray_descriptor.json
  user:
   secure: KtZRrzFiR1AM2nvZzt+yyypIvmeAH7Tr2otwDyveHafzBV/rfJ1fsSuw+hP8eaG4rzxlh3I//z/62xKUHmIZWTO9FjOoMnmSUyoeKoGVjIfSYSMMpt5hRFTA0HI8+O/kk9jvhdntRisHMz2V5KC/iX9phscxTMoQUfanGM9Eoi7RHJG/8dZG7QfrTtTExekOjDeGrqrjuj9gf8tlOxzca99AC7kb4QycBm4fAXm8XKkgGnhDaJPRkcEeXs9JUvCgUb67pegTyBSdeP3asPATJXDJ+WwkT+kKMBh9l87E2+3vCKmfh6eK1e2f8Itx2IZeTWHcwbn7Pb3700V60fQyMy/2UyWTnBr46yfZg+s/pr2YURKg69E9n1lMy17L4JaK4viEqReu2ARMS3TBhNAVoaW2MNlna+gvVKHVR+/1iU/cxmvxkBd5uOZ2p/30OYSXxYO6hvTiU/CAtqvKTYk+CA1BL7ZiuGsoc80mFmfmj8Gh7dGShk8pAGYSKz55y/QpVf4bu8utAGDHEyWfopEvdJxOo5kv4MX9KCHd3VsGhzJzrRMCUmfAFWB5OWR2bHTAUJW0amFHSSqVYy/xaqhRBXdxIOeXQmysAn7uilVl8UILdmqdZrx4Du/nEWkVUaGQYJ+tLr0ysHmKFuI2mqomwKjcjjZHyl9md/E1PHhz4xk=
  key:
   secure: jz18aBR118iAlHRaOJn5iRvbf7pnyd2MOLdihHvTeE/eO/RIysmGWBSquW1jzjpABE/5epmawuImPg2pNgTyog9S2Idv4r0nQKTfGQ355PsMSxFrO1vSpy60g6r1oaEMOVWgln7cRhBwgCS3rSwrJnhzGJiKQwkDnep6PJys2thoHN9ZL6RMXNZHqgYFjQXgRGoK8NS3qfd1tW+H5T8fXq9r9rNeD78ncPbixxHo9k8xm+Y7krNHIJTZjyY0szg1ZGguW4FeI8oCb2mnn+CVWzJInf1Ojlu7SXBkEm6c9U86ZpCgQuSXlkkBuEC+TOsHXBmBtE94A/vVt8FI9Nm1ijlGo+sMhTEqtouLg/Y9GKlDjDCalaxQQzVD4vhGNnOaTwk9YZUxHwwSe3wpIFZdlK+ZfLcvMEcQeijlY0gvlOfXqlqSzVttJhMCdcvGmZGLGRvA5xfoAGgvj2F0k4UXzRB32+COJEO58DTms03mGCUhXZ9JMrAd48wBy5T5GWgnxWNRhkLQlSIOGaSdspKCMiVmyNBvmrxmweFUNrbrahP5Q2H7Zmmf1thjW9dE4cP9RWkruLMGu0dGbxEKGJOKTp3eG2SZ86Z1iY50mowfgBNQUg1wu/MBfL/ZVvsya3UNBddZAC37orOh9dcD5EYfeJL5hmspBnyVtJM7pVljKYg=
env:
   global:
     - TOPDIR=/home/travis/build
     - PATH=$PATH:/opt/hermit/bin:$TOPDIR/x86/bin
