Document: gcc
Title: Debian gcc Manual
Author: <insert document author here>
Abstract: This manual describes what gcc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gcc/gcc.sgml.gz

Format: postscript
Files: /usr/share/doc/gcc/gcc.ps.gz

Format: text
Files: /usr/share/doc/gcc/gcc.text.gz

Format: HTML
Index: /usr/share/doc/gcc/html/index.html
Files: /usr/share/doc/gcc/html/*.html
